### ISSUE TITLE
Add support for favicon.ico

### ISSUE THREAD

**Issue by samumbach** [relevance/tarantula#11]
Retrieving /favicon.ico always yields a 404, even though the file exists in the public dir.  The file (and all files with the .ico extension) should be supported in the same way as other image and text formats.

(I sent a pull request w/ a patch for this a few minutes ago).

**Comment by samumbach** [comment]
Thanks for integrating the patch!

**Comment by cldwalker** [comment]
Seems to have been fixed by 076350dcda83ce0b636674ae22d3f34e16a986f3
