### ISSUE TITLE
relevance-tarantula 0.3.0 gem has not been built and published by github

### ISSUE THREAD

**Issue by samumbach** [relevance/tarantula#12]
Not sure if this is a general issue with github, but the 0.3.0 gem has not been built.  I pulled down the code, built, and tested with Gist - 16215 and everything looks okay.

http://hasmygembuiltyet.org/relevance/tarantula
http://gems.github.com/list.html

**Comment by ghost** [comment]
This looks like it is a github issue.  Some of our other gems have not built this weekend either.  Hopefully it will be resolved soon.

**Comment by ghost** [comment]
Friendly FYI: 0.3.0 still not built and published on github as far as I can tell.

**Comment by glv** [comment]
0.3.0 _still_ hasn't been build and published, but 0.3.3 has.  Use that instead.  :-)
