### ISSUE TITLE
Problem with InvalidHtmlHandler

### ISSUE THREAD

**Issue by ghost** [relevance/tarantula#14]
I keep getting invalid html errors on pages that are rendering successfully, in fact on EVERY path. Here's what the data result is on the report:

<pre>
uninitialized constant HTML::Document
</pre>

Sure enough is I head into invalid_html_handler.rb and comment out lines 8-13 it runs without issue. (And presumably without checking any html syntax.)

Couldn't find the reason why HTML::Document wasn't being loaded....ideas?
- Mark McSpadden

**Comment by cldwalker** [comment]
HTML::Document comes from activesupport. Works fine for activesupport 3.0.x. What version of AS were you using?

**Comment by cldwalker** [comment]
Closing. Feel free to reopen if still an issue.
