### ISSUE TITLE
Move rake tasks into gem lib directory

### ISSUE THREAD

**Issue by gorism** [relevance/tarantula#15]
Rather than have to vendor the gem to get access to the rake tasks, I wonder if you might follow a pattern I've seen with other gems (delayed_job and thinking_sphinx, specifically).  They have the actual rake tasks inside of a directory underneath lib, so that they're available once the gem has been loaded.  There is still a tasks file in the root of the gem directory, but that file simply loads the tasks definition from the lib directory.  With the rake tasks loaded, our application can then "require" them, without having to separately load a file containing those tasks.

Something to consider.  Vendoring the gem isn't ideal because it is so easy to update the gem but then not update the vendored version.  The approach that delayed_job and thinking_sphinx took avoids that issue.

**Comment by letronje** [comment]
Without this, whats the work around to make sure the rake tasks are available ?

**Comment by cldwalker** [comment]
Not an issue any more as they are under lib/ now.
