### ISSUE TITLE
ThreadError: thread tried to join itself, when running Tarantula test

### ISSUE THREAD

**Issue by jsheinis** [relevance/tarantula#16]
The following test fails at 'follow_redirect!' with ThreadError (stack trace below)

  def test_tarantula
    post '/session', :login => 'aaron', :password => 'monkey'
    assert_response :redirect
    assert_redirected_to '/home'
    follow_redirect!

```
tarantula_crawl(self)
```

  end

ThreadError: thread 0xb77fc1ac tried to join itself
    tarantula (0.3.3) [v] lib/relevance/tarantula/rails_integration_proxy.rb:33:in `send'
    tarantula (0.3.3) [v] lib/relevance/tarantula/rails_integration_proxy.rb:33:in`get'
    tarantula (0.3.3) [v] lib/relevance/tarantula/crawler.rb:122:in `send'
    tarantula (0.3.3) [v] lib/relevance/tarantula/crawler.rb:122:in`follow'
    tarantula (0.3.3) [v] lib/relevance/tarantula/link.rb:36:in `crawl'
    tarantula (0.3.3) [v] lib/relevance/tarantula/crawler.rb:99:in`crawl_the_queue'
    tarantula (0.3.3) [v] lib/relevance/tarantula/crawler.rb:92:in `do_crawl'
    tarantula (0.3.3) [v] lib/relevance/tarantula/crawler.rb:64:in`crawl'
    tarantula (0.3.3) [v] lib/relevance/tarantula/crawler.rb:60:in `times'
    tarantula (0.3.3) [v] lib/relevance/tarantula/crawler.rb:60:in`crawl'
    tarantula (0.3.3) [v] lib/relevance/core_extensions/test_case.rb:8:in `tarantula_crawl'
    /test/tarantula/tarantula_test.rb:17:in`test_tarantula'

**Comment by cldwalker** [comment]
Our CI is green for 3 versions of ruby and rails 3.0.10 - http://travis-ci.org/#!/relevance/tarantula

If you have a specific rails + ruby version I can look into this more

**Comment by cldwalker** [comment]
Closing. Feel free to reopen if still an issue.
