### ISSUE TITLE
Removal of String.chars method

### ISSUE THREAD

**Issue by robg** [relevance/tarantula#18]
I ran into problems the other day where some of my tests began failing due to a missing String.chars method, which I ended up tracing back to lib/relevance/core_extensions/string_chars_fix.rb.  From the comment in the file, I gather that there was some sort of bad interaction with rails 2.0.2, but I'm not sure what.  Removing this file from the tarantula "requires" fixed my immediate problem and I didn't see any problems in the tarantula run, so I was curious what the actual problem was that it was supposed to fix.  In any case, un-defining a core Ruby method seems like a pretty blunt way to fix a bug.

I'm running ruby 1.8.7 patch 249 with rails 2.3.8.

**Comment by cldwalker** [comment]
Agreed this isn't a great fix. Came from 7f968ee21b53d3502f0d70af4e3855152f69c65c. Won't remove till I've dug deeper on this. I will at least try to limit this to rails2.

**Comment by cldwalker** [comment]
@rsanheim Any objections to removing this remove_method? I've confirmed tests pass in rails3 and rails 2.3, which are the only rails versions I planned on supporting: http://travis-ci.org/#!/relevance/tarantula/builds/736771

**Comment by cldwalker** [comment]
@rsanheim Talked with Chad and decided to remove remove_method
@robg Fixed

**Comment by rsanheim** [comment]
Makes sense to me.  Thx for the fixes!

Sent from phonetron 9000

On Feb 24, 2012, at 2:52 PM, Gabriel Horner
reply@reply.github.com
wrote:
