### ISSUE TITLE
need to do 'touch MIT-LICENSE'?

### ISSUE THREAD

**Issue by apsheronets** [relevance/tarantula#19]
[komar@pavilion ~/src/tarantula]$ gem build tarantula.gemspec
WARNING:  RDoc will not be generated (has_rdoc == false)
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - MIT-LICENSE

**Comment by invernizzi** [comment]
they just moved that file to "LICENCE". update the gmespec

**Comment by cldwalker** [comment]
this isn't an issue any more
