### ISSUE TITLE
rake tarantula:setup fails, rails 3.1 application

### ISSUE THREAD

**Issue by jonathantelfer** [relevance/tarantula#23]
Added gem "tarantula" to the development group in gem file and the gem has installed with bundle install.

Running rake tarantula:setup gives the error "Don't know how to build task 'tarantula:test'"

**Comment by jgkite** [comment]
You can add this to your Rakefile as a workaround for right now:

```
load "relevance/tasks/tarantula_tasks.rake"
```

**Comment by jgkite** [comment]
The real fix is to add a Railtie that pulls in the rake tasks - patches welcome!
