### ISSUE TITLE
Could not run rake tarantula:setup

### ISSUE THREAD

**Issue by pa-s** [relevance/tarantula#25]
Could not use tarantula following the instructions in the github main page.

Here are the steps I followed. When trying to run rake tarantula:setup I get a rake aborted.

$ gem install tarantula
Fetching: htmlentities-4.3.1.gem (100%)
Fetching: hpricot-0.8.6.gem (100%)
Building native extensions.  This could take a while...
Fetching: tarantula-0.4.1.gem (100%)
Successfully installed htmlentities-4.3.1
Successfully installed hpricot-0.8.6
Successfully installed tarantula-0.4.1
3 gems installed
Installing ri documentation for htmlentities-4.3.1...
Installing ri documentation for hpricot-0.8.6...
Installing ri documentation for tarantula-0.4.1...
Installing RDoc documentation for htmlentities-4.3.1...
Installing RDoc documentation for hpricot-0.8.6...
Installing RDoc documentation for tarantula-0.4.1...

$ #!sh

$ rake tarantula:setup --trace
rake aborted!
Don't know how to build task 'tarantula:setup'
/Users/sarah/.rvm/gems/ruby-1.9.2-p290@cw/gems/rake-0.9.2.2/lib/rake/task_manager.rb:49:in `[]'
/Users/sarah/.rvm/gems/ruby-1.9.2-p290@cw/gems/rake-0.9.2.2/lib/rake/application.rb:115:in`invoke_task'
/Users/sarah/.rvm/gems/ruby-1.9.2-p290@cw/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/sarah/.rvm/gems/ruby-1.9.2-p290@cw/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/Users/sarah/.rvm/gems/ruby-1.9.2-p290@cw/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/sarah/.rvm/gems/ruby-1.9.2-p290@cw/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/Users/sarah/.rvm/gems/ruby-1.9.2-p290@cw/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/sarah/.rvm/gems/ruby-1.9.2-p290@cw/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`block in run'
/Users/sarah/.rvm/gems/ruby-1.9.2-p290@cw/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/sarah/.rvm/gems/ruby-1.9.2-p290@cw/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/Users/sarah/.rvm/gems/ruby-1.9.2-p290@cw/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/sarah/.rvm/gems/ruby-1.9.2-p290@cw/bin/rake:19:in`load'
/Users/sarah/.rvm/gems/ruby-1.9.2-p290@cw/bin/rake:19:in `<main>'

**Comment by cldwalker** [comment]
Seeing this as well. I'll look into it on Friday.

**Comment by ayrton** [comment]
For some reason I experience the same issue right now (either with the latest release or with the current source of git).

**Comment by SkyWriter** [comment]
Probably too late, but in case somebody else stumbles upon this:

```
gem 'tarantula', :require => 'tarantula-rails3'
```

Solved my issue with Rails 3.2.6.

**Comment by bquorning** [comment]
@SkyWriter Thanks! I stumbled, and you caught me.

**Comment by ldenman** [comment]
@SkyWriter I have added the note to the readme. Thanks.
