### ISSUE TITLE
rake tarantula:report does not open HTML report when a test fails

### ISSUE THREAD

**Issue by ghost** [relevance/tarantula#4]
"rake tarantula:report" only opens the HTML report if all Tarantula tests pass.  (When all tests pass, you don&rsquo;t usually need to look at the report.  You really want to see the report when tests are failing.) 

"rake tarantula:report" should always show the HTML report, regardless of whether the Tarantula tests pass or fail.

[original LH ticket](http://relevance.lighthouseapp.com/projects/17868/tickets/11)

 This ticket has 0 attachment(s).

**Comment by jasonrudolph** [comment]
rake tarantula:report now always open the HTML report even if there are test failures. Closed by 61ab75f87de4faf8e285ecc307a85e8b56bf7fb4.
