### ISSUE TITLE
Request to add support and documentation to run with Rspec.

### ISSUE THREAD

**Issue by ghost** [relevance/tarantula#5]
It would be nice to have Tarantula work with Rspec as well as documentation on how to implement an example specification.

[original LH ticket](http://relevance.lighthouseapp.com/projects/17868/tickets/7)

 This ticket has 0 attachment(s).

**Comment by ghost** [comment]
**Request to add support and documentation to run with Rspec.**

For now, you can still run it with the rake tarantula:test command even if you are using rspec. 

What needs to be done to make this run with all the specs I need to get Cucumber integration hacked in.  I am going to get together with Chad and see if we can get this working.

 by Aaron Bedra

**Comment by ghost** [comment]
**Request to add support and documentation to run with Rspec.**

 by Aaron Bedra

**Comment by ghost** [comment]
**Request to add support and documentation to run with Rspec.**

 by Aaron Bedra

**Comment by notdevinclark** [comment]
I see that this was asked about 4 years ago. Has there been any progress towards this feature or plans to implement it. It would be greatly appreciated since I primarily test using Rspec, Factory_Girl, Capybara, etc. instead of using fixtures. I have been looking all over the internet for anyone who has already tried to do this or at least documentation on a jerry-rigged implementation but have come up empty handed.

**Comment by phildionne** [comment]
Same here, an example usage using Factory_Girl and would be much appreciated.

**Comment by yagudaev** [comment]
+1 having the same problem here.

Has anyone created a fork to support Rspec? There have been no commits for just over a year now, is this project still active?

**Comment by malachaifrazier** [comment]
Guess not...

**Comment by yagudaev** [comment]
Yes this repo seems pretty dead. It is a shame because a lot of the ideas here are really good.

I tried it with rails 4.1 and it never worked. Only works with 3.2.

**Comment by malachaifrazier** [comment]
I have yet to find a fork if this that works well with Rspec & Rails 3.x &&
Rails 4.x. Have you had any luck?

On Wednesday, July 16, 2014, Michael Yagudaev notifications@github.com
wrote:

> Yes this repo seems pretty dead. It is a shame because a lot of the ideas
> here are really good.
> 
> I tried it with rails 4.1 and it never worked. Only works with 3.2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/relevance/tarantula/issues/5#issuecomment-49238030.

## 

Malachai Frazier @ _DetroitRails & Butterburn LLC_.
thefounder@detroitrails.co
_detroitrails.co http://detroitrails.co_
@DetroitRails & @CaptCussa

**Comment by rsanheim** [comment]
This is open source, pull requests are welcome :smile:.
